# Generated by Django 5.2.8 on 2025-11-22 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodMetadata",
            fields=[
                ("index", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("ingredients", models.TextField()),
                ("directions", models.TextField(blank=True, null=True)),
                ("ner", models.TextField(blank=True, db_column="NER", null=True)),
            ],
            options={
                "db_table": "food_metadata",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FoodAdding",
            fields=[
                ("index_temp", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("ingredients", models.TextField()),
                ("directions", models.TextField(blank=True, null=True)),
                ("ner", models.TextField(blank=True, db_column="NER", null=True)),
                (
                    "last_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "food_adding",
            },
        ),
    ]
