# Generated by Django 5.2.8 on 2025-11-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_recommend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodadding",
            options={"managed": False},
        ),
    ]
